// Generated by nuxt-seo-utils

import type { RobotsContext } from '#robots/types'

declare module 'nitropack/types' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}

declare module 'nitropack' {
  interface NitroRouteRules {
     seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
     head?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
  interface NitroRouteConfig {
    seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable
    head?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').Head
  }
}


declare module '@nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

declare module 'nuxt/schema' {
  interface AppHeadMetaObject { seoMeta?: import('../../node_modules/.pnpm/nuxt-seo-utils@8.1.11_@nuxt+schema@4.4.5_esbuild@0.28.0_lightningcss@1.32.0_magicast@0._a26f4e0b054d2c9e3979e0c3686c200b/node_modules/nuxt-seo-utils/dist/runtime/types').MetaFlatSerializable }
}

export {}
