// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxtseo-shared@0.9.0_468a7c970e76c86f98842a06ddba8a2a/node_modules/nuxtseo-shared/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxtseo-shared@0.9.0_468a7c970e76c86f98842a06ddba8a2a/node_modules/nuxtseo-shared/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
