// Builds the body of a generated .cjs wrapper that executes a copied .sh hook
// script. The wrapper is fully self-contained (no mewkit imports at runtime) and
// points at a script copied under the Codex output tree, so deleting the source
// .claude/ tree after migration does NOT break the migrated hook.
//
// Env rewrite: Claude Code exports $CLAUDE_PROJECT_DIR (and other $CLAUDE_* vars)
// that Codex does not. The wrapper injects a computed project root for the common
// vars from a LITERAL table (never content-derived interpolation), then execs the
// copied script via /bin/sh with an argv ARRAY (execFile-style) so a project root
// containing spaces or shell metacharacters is passed as one literal argument.
//
// Deny protocol (documented at https://developers.openai.com/codex/hooks):
// a PreToolUse hook denies via exit code 2 + reason on stderr (direct parity with
// Claude's exit-2 convention), or the {"decision":"block",...} shape. The wrapper
// preserves the child's exit code and, for deny-capable events, converts exit 2
// into the structured permissionDecision:"deny" payload Codex expects.

interface ShWrapperOptions {
	copiedScriptPath: string;
	scrubRulesJson: string;
	timeoutMs: number;
}

export function buildShWrapperScript(originalPath: string, options: ShWrapperOptions): string {
	const escapedScriptPath = JSON.stringify(options.copiedScriptPath);
	const escapedOriginal = JSON.stringify(originalPath);

	return `#!/usr/bin/env node
// AUTO-GENERATED by the migration tooling — DO NOT EDIT
// Codex shell-hook compatibility wrapper for:
//   ${originalPath}
// Executes the copied script (self-contained under the Codex tree).
"use strict";

const { spawnSync } = require("node:child_process");
const path = require("node:path");

const COPIED_SCRIPT = ${escapedScriptPath};
const ORIGINAL_HOOK = ${escapedOriginal};
const SCRUB_RULES = ${options.scrubRulesJson};
const HOOK_TIMEOUT_MS = ${options.timeoutMs};

// Computed project root: the Codex tree is <root>/.codex/hooks/scripts/<file>,
// so the project root is four levels up from the copied script. Derived from a
// literal directory-depth table, never from string interpolation of user input.
function computeProjectRoot() {
  if (process.env.CODEX_PROJECT_DIR) return process.env.CODEX_PROJECT_DIR;
  const scriptsDir = path.dirname(COPIED_SCRIPT);           // .codex/hooks/scripts
  const hooksDir = path.dirname(scriptsDir);                // .codex/hooks
  const codexDir = path.dirname(hooksDir);                  // .codex
  return path.dirname(codexDir);                            // <project root>
}

function rewrittenEnv() {
  const projectRoot = computeProjectRoot();
  const env = Object.assign({}, process.env);
  // Bridge the Claude-only vars a .sh hook may read to Codex-available values.
  if (env.CLAUDE_PROJECT_DIR === undefined) env.CLAUDE_PROJECT_DIR = projectRoot;
  if (env.CLAUDE_PLUGIN_DATA === undefined) env.CLAUDE_PLUGIN_DATA = path.join(projectRoot, ".codex");
  return env;
}

function getEventFromStdin(stdinData) {
  try {
    const parsed = JSON.parse(stdinData);
    return parsed.hook_event_name || parsed.event || null;
  } catch {
    return null;
  }
}

function eventSupportsDeny(rules) {
  if (!rules || rules.allowedPermissionValues === null || rules.allowedPermissionValues === undefined) return false;
  return rules.allowedPermissionValues.indexOf("deny") !== -1;
}

function emitDeny(reason) {
  process.stdout.write(JSON.stringify({
    permissionDecision: "deny",
    reason: reason && reason.length > 0 ? reason : "Hook blocked this operation",
  }));
  process.exit(0);
}

function main() {
  const stdinChunks = [];
  process.stdin.on("data", (chunk) => stdinChunks.push(chunk));
  process.stdin.on("end", () => {
    const stdinData = Buffer.concat(stdinChunks).toString("utf8");
    const event = getEventFromStdin(stdinData);
    const rules = event && SCRUB_RULES[event];

    // argv ARRAY — the copied script path is one literal argument, so a project
    // root containing spaces or shell metacharacters is never re-parsed by a shell.
    const result = spawnSync("/bin/sh", [COPIED_SCRIPT], {
      input: stdinData,
      env: rewrittenEnv(),
      encoding: "utf8",
      timeout: HOOK_TIMEOUT_MS,
    });

    if (result.error) {
      if (result.stderr) process.stderr.write(result.stderr);
      process.exit(1);
    }

    const stderrText = (result.stderr || "").toString();
    const rawOutput = (result.stdout || "").toString();
    const exitCode = result.status == null ? 1 : result.status;
    const isBlockSignal = exitCode === 2 && eventSupportsDeny(rules);

    if (isBlockSignal) {
      const reason = (rawOutput.trim() || stderrText.trim());
      return emitDeny(reason);
    }

    if (stderrText) process.stderr.write(stderrText);
    if (rawOutput) process.stdout.write(rawOutput);
    process.exit(exitCode);
  });
}

main();
`;
}
