// One-time runner: port the authored `.claude/` tree into the `modules/codex/`
// bundle (agents/ + skills/). Authored AGENTS.md / config.toml / hooks.json /
// hooks/ and manifest.json are left in place; only the derived agents/ and skills/
// trees are regenerated. Run: `npx tsx packages/mewkit/scripts/run-codex-port.ts`.
//
// FROZEN: the Codex bundle is now hand-authored, not regenerated by this semantic
// porter. Running it would overwrite hand-authored agents/ and skills/ content with
// a fresh mechanical port. It exits non-zero unless MEWKIT_PORTER_UNFREEZE=1 is set,
// so an accidental run cannot clobber authored content. The porter is deleted only
// after the authored bundle passes its cutover gates.
// Context: plans/260723-1701-codex-native-bundle-implementation.
import { rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { portAll } from "../src/migrate/modules/porter/port-claude-to-codex.js";

if (process.env.MEWKIT_PORTER_UNFREEZE !== "1") {
	console.error(
		"porter frozen — the Codex bundle is hand-authored; regenerating it would overwrite authored agents/ and skills/ content.\n" +
			"See plans/260723-1701-codex-native-bundle-implementation. Set MEWKIT_PORTER_UNFREEZE=1 to override.",
	);
	process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const claudeDir = join(repoRoot, ".claude");
const outDir = join(here, "..", "src", "migrate", "modules", "codex");

for (const derived of ["agents", "skills"]) rmSync(join(outDir, derived), { recursive: true, force: true });
const summary = portAll(claudeDir, outDir);
console.log(`Ported → ${outDir}`);
console.log(JSON.stringify(summary, null, 2));
